### ISSUE TITLE
Bakery対応

### ISSUE THREAD

**Issue by shivaduke28** [shivaduke28/kanikama#18]
BakeryLightとかいうのが使われているらしい

**Comment by cannorin** [comment]
これはとてもかなり欲しいので応援しています

**Comment by shivaduke28** [comment]
## BakeryLightMeshメモ

- MeshRenderer or AreaLightと一緒に使う
- マテリアルに関係なく動く（Meshしかみてない）
- 複数マテリアルとかも関係ない


BakeryLightMeshがついてる場合
- MeshRenderer
  - マテリアルの色をもらう用にする（ColorSourceはマテリアル）
  - マテリアルが複数ある場合も一つ目だけでいい
  - 複数ある場合も1つだけ使うようにする
  - ウドンが判断するの？？？
  - Bakery/Lightシェーダー
    - _Color * _Intensity がほしい値になる
    - Standardシェーダーと一緒じゃなくて困る
    - _EmissionColorを見るようにしたい
    - Kanikama/Lightシェーダーを用意する
      - Udonは_EmissionColorしか見ないようにする
      - _EMISSIONフラグを見るようにしたい
      - ひとつめだけフラグを立てるようにすれば一応対応できそう
        - Editor拡張でやる
- Light
  - ライトの色を使う
- どちらの場合も光源はひとつだけなのでLightSourceでよい


BakeryLightMeshがついていないMeshRenderer
- これまで通りマテリアルごとにベイクする
- Udonはこれまで通りなので問題なさそう
- KanikamaRendererがそのまま使える
